# Generated by Django 4.0.1 on 2022-01-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_skill_level_alter_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'BEGINNER'), ('intermediate', 'INTERMEDIATE'), ('expert', 'EXPERT')], default='intermediate', max_length=15),
        ),
    ]
