# Generated by Django 4.0.1 on 2022-01-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0007_alter_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('experience', 'EXPERIENCE'), ('skill', 'SKILL'), ('education', 'EDUCATION')], default='experience', max_length=15),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'BEGINNER'), ('expert', 'EXPERT'), ('intermediate', 'INTERMEDIATE')], default='intermediate', max_length=15),
        ),
    ]
